name: Zscaler - Application - Top Application Names
visualization:
  options: {}
  type: pie-chart
$schema: https://schemas.humio.com/query/v0.3.0
timeInterval:
  isLive: false
  start: 1d
queryString: |-
  #Vendor="zscaler" Vendor.product="NSS"
  | top(Vendor.appname)
